# Generated by Django 4.2.3 on 2023-08-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_expiredmedicinelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sales_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
