# Generated by Django 4.2.3 on 2023-08-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_sale_sales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sales_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
